# docker-compose.yml
version: '3.8'

services:
  apple-music-bot:
    build: .
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt
    environment:
      - BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN
      - PUBLIC_MODE=True
    restart: unless-stopped
